#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys
import torch
from transformers import DPTFeatureExtractor, DPTForDepthEstimation
from diffusers import ControlNetModel, DiffusionPipeline, AutoencoderKL

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import CONTROL_MODEL, VAE_MODEL, MODEL_NAME, FEATURE_NAME, CONTROL_CACHE, VAE_CACHE, MODEL_CACHE, FEATURE_CACHE

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

# depth_estimator = DPTForDepthEstimation.from_pretrained(FEATURE_NAME)
# depth_estimator.save_pretrained(FEATURE_CACHE)

# feature_extractor = DPTFeatureExtractor.from_pretrained(FEATURE_NAME)
# feature_extractor.save_pretrained(FEATURE_CACHE)

controlnet = ControlNetModel.from_pretrained(
    CONTROL_MODEL,
    variant="fp16",
    use_safetensors=True,
    torch_dtype=torch.float16
)
controlnet.save_pretrained(CONTROL_CACHE)

# # Download SDXL-VAE-FP16-Fix
# better_vae = AutoencoderKL.from_pretrained(
#     VAE_MODEL,
#     torch_dtype=torch.float16,
# )
# better_vae.save_pretrained(VAE_CACHE, safe_serialization=True)

# # SD-XL-Base-1.0
# pipe = DiffusionPipeline.from_pretrained(
#     MODEL_NAME,
#     vae=better_vae,
#     torch_dtype=torch.float16,
#     use_safetensors=True,
#     variant="fp16",
# )
# pipe.save_pretrained(MODEL_CACHE, safe_serialization=True)
